# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170522_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracheque',
            name='decimoTerceiro',
            field=models.NullBooleanField(verbose_name='Décimo Terceiro'),
        ),
    ]
